config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    resources :tags, only: :index
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :users, only: %i[new create destroy edit update]

    resources :tags, only: :create

    resource :session, only: %i[new create destroy]

    resources :questions do
      resources :answers, except: %i[new show]
      resources :comments, only: %i[create destroy]
    end

    resources :answers, except: %i[new show] do
      resources :comments, only: %i[create destroy]
    end

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    root 'pages#index'
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Commentable
  include Authorship
  belongs_to :question
  belongs_to :user
  validates :body, presence: true, length: { minimum: 5 }

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include ActionView::RecordIdentifier
  include QuestionsAnswers
  before_action :set_question!
  before_action :set_answer!, except: :create
  before_action :authorize_answer!
  after_action :verify_authorized

  def update
    if @answer.update answer_update_params
      flash[:success] = 'Answer updated!'
      redirect_to question_path(@question, anchor: dom_id(@answer))
    else
      render :edit
    end
  end

  def edit; end

  def create
    @answer = @question.answers.build answer_create_params
    if @answer.save
      flash[:success] = 'Answer created!'
      redirect_to question_path(@question)
    else
      load_question_answers(do_render: true)
    end
  end

  def destroy
    @answer.destroy
    if @answer.destroy
      flash[:success] = 'Answer deleted!'
      redirect_to question_path(@question)
    end
  end

  private

  def set_question!
    @question = Question.find params[:question_id]
  end

  def set_answer!
    @answer = @question.answers.find params[:id]
  end

  def answer_create_params
    params.require(:answer).permit(:body).merge(user_id: current_user.id)
  end

  def answer_update_params
    params.require(:answer).permit(:body)
  end

  def authorize_answer!
    authorize(@answer || Answer)
  end
end

app/views/answers/_answer.html.erb
<%= tag.article class: 'mb-3 card', id: dom_id(answer) do %>
  <div class="row-g-0">
    <div class="col-sm-auto text-sm-center align-self-center">
      <%= answer.user.gravatar size:30, css_class: 'd-block'%>
      <%= answer.user.name_or_email %>
    </div>
    <section class="card-text">
      <small><time datetime="<%= answer.created_at %>">
        <%= answer.formatted_created_at %>
      </time></small>

      <div class="mt-2 mb-3">
        <%= sanitize answer.body %>
      </div>
    </section>
    </div>
    <div>
      <% if policy(answer).edit? %>
    <%= link_to 'Edit', edit_question_answer_path(question, answer),
                class: 'btn btn-info btn-sm' %>
        <% end %>
      <% if policy(answer).destroy? %>
    <%= link_to 'Delete', question_answer_path(question, answer), class: 'btn btn-danger btn-sm',
                data: {method: :delete, confirm: "Are you sure?"} %>
        <% end %>
  </div>
<% end %>

<%= render 'comments/commentable', commentable: answer, comment: @comment,
           html_id: dom_id(answer, 'comment_form') %>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>

<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control', required: true %>
    </div>
  </div>

  <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% currently_at 'Answer' %>
<h1>Edit answer</h1>

<%= render 'form' %>